### ISSUE TITLE
iot2050 don't reboot

### ISSUE THREAD

**Issue by serafimdasaudade** [siemens/meta-iot2050#112]
Hi,

I have built iot2050 image from the latest github commit.  
After I execute the command "reboot" over shh.
The led STAT stop blinking and turn off and stay in this state forever. 
For the iot2050 start booting I need to press RESET button our remove the power supply.

Best Regards,

**Comment by jan-kiszka** [comment]
Yeah, kind of a known issue of the current 4.19 kernel, not seen with the upstream 5.x kernel yet.

How are you able to reproduce the issue? I'm only able to trigger it eventually after writing lots of data to the eMMC - which makes it slow to debug.

**Comment by serafimdasaudade** [comment]
I'm using IOT2050 basic with 32GB sdcard.
This issue happen every time I execute the command reboot. 

Best Regards,

**Comment by Ben-WD** [comment]
Same problem, can reproduce this easily, too.

**Comment by Webbeh** [comment]
I am able to reproduce the issue with the basic, non-emmc model, using this image : 
https://glassey.dev/iot2050.img

I then compiled a fresh one again which seems to work without hanging on reboot (either on microSD or flashed on eMMC) : 
https://glassey.dev/iot2050-2.img

I didn't try to use the first image in an eMMC model or the second image on a standard model.

Hope it helps.

**Comment by Ben-WD** [comment]
Did some testing today using the Debian example image from here: https://github.com/siemens/meta-iot2050/actions/runs/622988791

The device reboots without problems when using that image. As soon as updates are installed (`apt-get update && apt-get upgrade`), the device hangs on reboot. There's no kernel panic, the device just stops:

```
[  OK  ] Reached target Shutdown.
[  OK  ] Reached target Final Step.
[  OK  ] Started Reboot.
[  OK  ] Reached target Reboot.
[  312.653090] systemd-shutdown[1]: Syncing filesystems and block devices.
[  312.976637] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[  312.991418] systemd-journald[1976]: Received SIGTERM from PID 1 (systemd-shutdow).
[  313.016922] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[  313.032286] systemd-shutdown[1]: Unmounting file systems.
[  313.041064] [3541]: Remounting '/' read-only in with options '(null)'.
[  313.154866] EXT4-fs (mmcblk0p1): re-mounted. Opts: (null)
[  313.188949] systemd-shutdown[1]: All filesystems unmounted.
[  313.194565] systemd-shutdown[1]: Deactivating swaps.
[  313.199755] systemd-shutdown[1]: All swaps deactivated.
[  313.205002] systemd-shutdown[1]: Detaching loop devices.
[  313.213764] systemd-shutdown[1]: All loop devices detached.
[  313.219353] systemd-shutdown[1]: Detaching DM devices.
[  313.239747] reboot: Restarting system
```

**Comment by Webbeh** [comment]
Reproduced the same on both the advanced and the standard IOT. Reboots fine until you `apt upgrade`.

**Comment by jan-kiszka** [comment]
It's complicated: I tried that pattern as it sounded appealingly simple, even used the image @Ben-WD suggested, but it does not trigger for me. Back to my pattern (eMMC installation on first boot)...

**Comment by jan-kiszka** [comment]
Ok, I've instrumented the kernel in its reboot path, and we are either stuck on calling or inside the firmware (PSCI, implemented by Trusted Firmware A). Interestingly, the issue is also present with a newer firmware version I've built locally. Let's see if I can follow the call from there...

**Comment by jan-kiszka** [comment]
It's nasty - and not yet understood: https://lists.trustedfirmware.org/pipermail/tf-a/2021-April/001076.html

**Comment by jan-kiszka** [comment]
Just thought about this again and found a simpler pattern to reproduce it here:
```
# dd if=/dev/mmcblk1 of=/dev/null bs=2M count=1024
# reboot
```
As the same thing also works with a USB stick, thus a rather different I/O path, this clearly points to a corruption of the "secure" memory used by TF-A and OP-TEE via Linux' page cache.

I bet there is a bug in TF-A that causes it to forget about some pieces of its memory, neither declaring it secure nor adding it to the reservation that should prevent Linux from touching it as RAM...

**Comment by Ben-WD** [comment]
Tested the image from #116 and can confirm that reboots now are working flawlessly 👍🏻 

@jan-kiszka Is it possible to patch devices that are already out there without replacing the complete Linux image? Or is there any ETA for a new stable image that would justify to swap all images (which means that all devices must be provisioned again)

**Comment by jan-kiszka** [comment]
@Ben-WD You only need to update the device tree files (`/usr/lib/linux-<version>/ti/*iot2050*.dtb`). And the originally released images were not affected by this, it was a regression in the development tree only.

A new image release is indeed in work, tests and release procedures running. Don't ask me for an exact date, though.

**Comment by Webbeh** [comment]
What if we do ask for an exact date ? :)

Thanks for the patch though. Any way to know which package update messed up the reserved memory addresses in particular so we can just ignore their update for now ?

Or could it happen with any package update ?

**Comment by jan-kiszka** [comment]
Q1: `/* no comment */` :wink:

Q2: Looks like this happened in e18d2a5fb9fd3fdf7dbe44e8e212b2dc91fda843.

Q3: The issue of not reserving special memory comes from that update of the kernel package. Others are not causing it. Still, the real issue remains the unprotected OP-TEE memory - we are on that one as well.
