### ISSUE TITLE
Timezone selection menu

### ISSUE THREAD

**Issue by kumajaya** [siemens/meta-iot2050#119]
Please add timezone selection menu in IOT2050 Setup - OS Settings. Thank you.

**Comment by jan-kiszka** [comment]
Please have a look at that pull request if that works for you (just copy the resulting iot2050setup.py to /usr/bin/iot2050setup on the device).

**Comment by kumajaya** [comment]
Nice! It's even better after I install dialog with "apt-get install dialog".
