### ISSUE TITLE
Atheros AR9271 WiFi USB dongle doesn't work.

### ISSUE THREAD

**Issue by Davide3i** [siemens/meta-iot2050#120]
Hello.
I'm trying to use a WiFi USB dongle (ALFA AWUS036NHA), which uses chipset Atheros AR9271. I've tested and used it with many other Linux distros without any kind of issue.
I've installed _[firmware-atheros](https://packages.debian.org/buster/firmware-atheros)_, _lsusb_ correctly detects the WiFi USB dongle, but I cannot see it with _ifconfig_.

<img width="733" alt="lsusb" src="https://user-images.githubusercontent.com/4678930/115973152-68d2c480-a542-11eb-931d-0ee6232b667f.png">
<img width="452" alt="ifconfig" src="https://user-images.githubusercontent.com/4678930/115973166-83a53900-a542-11eb-9d05-5179fa84adc0.png">

**Comment by jan-kiszka** [comment]
This requires CONFIG_ATH9K_HTC which is actually set (to 'm') since day 1. What does the kernel console report (dmesg) when you plug in the stick?

**Comment by Davide3i** [comment]
I can read this. Looks like it gets disconnected as soon as I connect it.

```
[  238.260414] usb 3-1: USB disconnect, device number 3
[  255.947201] usb 3-1: new high-speed USB device number 4 using xhci-hcd
[  256.111663] usb 3-1: New USB device found, idVendor=0cf3, idProduct=9271, bcdDevice= 1.08
[  256.111678] usb 3-1: New USB device strings: Mfr=16, Product=32, SerialNumber=48
[  256.111683] usb 3-1: Product: UB91C
[  256.111688] usb 3-1: Manufacturer: ATHEROS
[  256.111693] usb 3-1: SerialNumber: 12345
```

**Comment by jan-kiszka** [comment]
...but then it is correctly recognized by the USB core. No further printing after that? Does lsmod list ath9k_htc & Co.?

**Comment by Davide3i** [comment]
No other messages after that.

Moreover...

`
:~$ lsmod | grep ath
{no output}`

Thank you for your help.

**Comment by jan-kiszka** [comment]
Does `modprobe ath9k_htc` work?
What image version are you using?

**Comment by Davide3i** [comment]
`sudo modprobe ath9k_htc
modprobe: FATAL: Module ath9k_htc not found in directory /lib/modules/4.19.94-rt39
`

I suppose this is the image version, right?
`v2.1(release):v2.1-421-g996d37930-dirty
`

**Comment by jan-kiszka** [comment]
Ok, Industrial OS. Then you are actually on the wrong issue tracker because the kernel config of that image is not managed here. Please file a request via the support forum.

**Comment by Davide3i** [comment]
Oh, I'm sorry. Thank you.
