### ISSUE TITLE
Modem Manager could not reconnect after connection failure of bad signal

### ISSUE THREAD

**Issue by applea9** [siemens/meta-iot2050#124]
Hi,

I met a problem with 4G connection in IOT2050, the 4G module used is quectel EC20. In my test, when the 4G signal becomes bad,  the 4G connection will fail. But when the signal quality becomes good, the 4G connection could not reestablish.

the syslog is as following:

![modem_manager](https://user-images.githubusercontent.com/9065075/116202351-0dd0e580-a76d-11eb-8fab-8628f6f6586d.PNG)

Any ideas about this problem, thanks for your help!

**Comment by AsuraZeng** [comment]
Hi
you can try to modify the file under `/etc/NetworkManager/system-connections/cellular-4g`
autoconnect from false to true

**Comment by applea9** [comment]
> Hi
> you can try to modify the file under `/etc/NetworkManager/system-connections/cellular-4g`
> `autoconnect` from false to true

I have set autoconnect to true. I can see modem manager is continuously retrying.

**Comment by AsuraZeng** [comment]
do you have connected antenna on the 4G module?

**Comment by applea9** [comment]
> do you have connected antenna on the 4G module?

Yes I have. But in the test, in order to simulate the bad signal, I uninstalled the 4G antenna. And after the connection is failed, I install the antenna back to the 4G module.

**Comment by AsuraZeng** [comment]
we are now looking into it, will respond shortly

**Comment by applea9** [comment]
In the test only IOT2050 advanced has this issue.

**Comment by AsuraZeng** [comment]
Could you pls contact me through email:  chao.zeng@siemens.com

**Comment by AsuraZeng** [comment]
Hi
pls have a try on branch #136

**Comment by applea9** [comment]
It works well now, thanks.
