### ISSUE TITLE
Example Ethernet Configuration

### ISSUE THREAD

**Issue by simonabler** [siemens/meta-iot2050#14]
> The example image starts with the IP 192.168.200.1 preconfigured on the first Ethernet interface, and use DHCP at another. You can use ssh to connect to the system.

It was the other way around. P2 was preconfigured with 192.168.200.1

**Comment by simonabler** [comment]
Interface X1 P2 Port is eth0.
eth1 is accessable on X1 P1. 
It is confusing.

**Comment by jan-kiszka** [comment]
That is a good point... I'm running my box without cover so I didn't notice this "detail" yet. @johnson325, can we simply flip that for the next release or is that too late now?

**Comment by applea9** [comment]
In IOT2040, X1P1LAN is preconfigured with 192.168.200.1, and X2P1LAN is preconfigured with DHCP mode.

**Comment by johnson325** [comment]
> That is a good point... I'm running my box without cover so I didn't notice this "detail" yet. @johnson325, can we simply flip that for the next release or is that too late now?

Technically, it's possible. I'll try to do the alignment internally.
