### ISSUE TITLE
Implement open62541 OPC UA library

### ISSUE THREAD

**Issue by Venomz101** [siemens/meta-iot2050#146]
Hi!

Made a forum post on the Siemens IOT2050 forum about this and was recommended to open an issue here.

I'd like a OPC UA library (open62541 was recommended) implemented into the library, just like the way Mosquitto broker runs on localhost.

When testing alot of different scenarios with the Node-RED OPC UA Server, I found it to be pretty crude and raw and faced many annoying errors during scenario testing, I wasn't really happy with how the Node-RED OPC UA Server was operating, really unstable (client works great though!). 

So this is why I am looking for something more similiar to the Mosquitto broker running on localhost which works great.

Would this be possible?

**Comment by BaochengSu** [comment]
Have you tried this?
https://open62541.org/doc/current/installing.html#debian
