### ISSUE TITLE
Kernel 5.10 image does not boot

### ISSUE THREAD

**Issue by mfloiot** [siemens/meta-iot2050#200]
Hi, 
I have tried to get the latest master with Kernel 5.10.x on my iot2050-advanced PG1 running. 

With the previous Version (Kernel 4.19.*) my device boots with ti/k3-am6528-iot2050-advanced-oldfw.dtb devicetree. The current master does not provide this device tree anymore. BTW wic/iot2050.wks.in@master still references the *oldfw.dtb.

If I use ti/k3-am6528-iot2050-advanced.dtb from current master the system stops booting (see [boot-5.10.log](https://github.com/siemens/meta-iot2050/files/7351075/boot-5.10.log)).

I did not update the u-boot so far. 
Do I need update my device before using the current master?
Any help appreciated...

**Comment by jan-kiszka** [comment]
Yes, as the warning issued during build tells you: Only the not-yet-released new firmware allows to boot the 5.10 kernel. Current firmware requires 4.19 still.

Thanks for noting the oldfw.dtb left-over. We'll clean this up.

**Comment by mfloiot** [comment]
Are you planing to support the old firmware (is firmware equal to u-boot?) in future? Or will the new kernel be a breaking change forever.

**Comment by jan-kiszka** [comment]
TI changed the ABI of the sysfw (system management firmware), and we have to follow in that path. So: yes, we are breaking support for older firmware.

The 4.19 kernel was a special beast that supported both the old and the new sysfw, but this cannot be maintained when moving to the upstream kernel which we do with 5.10+. Except for the Ethernet driver, the IOT2050 is now fully supported by the upstream kernel - but only with new firmware.
