### ISSUE TITLE
Example image - linux-image-5.10.64 missing

### ISSUE THREAD

**Issue by MickaelDelanoe** [siemens/meta-iot2050#206]
Hi,

I tried to build an exemple image with Isar.
I work on macOS, so I install Debian 11 in Virtual Box and then I install docker on it and run `./kas-container build kas-iot2050-example.yml`

After burned my image`$ sudo dd if=build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic.img of=/dev/sdb bs=4M oflag=sync` and boot it, I got an issue.
The image do not run correctly, There is a trouble with  `linux-image-5.10.64` file during boot/run : `** File not found /usr/lib/linux-image-5.10.64/ **`

But the example image from SIOS works well ...

__On UART debug I got__ :

 1. With my own build on VirtualBox
```
Found U-Boot script /boot/boot.scr
704 bytes read in 1 ms (687.5 KiB/s)
## Executing script at 83000000
Loading /usr/lib/linux-image-5.10.64/...
** File not found /usr/lib/linux-image-5.10.64/ **
Loading /boot/vmlinux-5.10.64...
17897480 bytes read in 4760 ms (3.6 MiB/s)
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
SCRIPT FAILED: continuing...
```

 2. With `109780231_IOT2050_Example_Image_V1.1.1.zip (658,6 MB)(SHA-256)` from SIOS
```
Found U-Boot script /boot/boot.scr
889 bytes read in 0 ms
## Executing script at 83000000
Loading /usr/lib/linux-image-4.19.94/ti/k3-am6548-iot2050-advanced-oldfw.dtb...
78384 bytes read in 11 ms (6.8 MiB/s)
Loading /boot/vmlinux-4.19.94...
13604872 bytes read in 6207 ms (2.1 MiB/s)
## Flattened Device Tree blob at 82000000
   Booting using the fdt blob at 0x82000000
   Loading Device Tree to 00000000fdeb0000, end 00000000fdec622f ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
```

Do you know why one file is missing and is not the same between both image *(/usr/lib/linux-image-)* ?

Best Regards,

**Comment by MickaelDelanoe** [comment]
Hello,
I tried your command and rebuild after, but it seems I have the same error

```
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building openssl using existing ./openssl_1.1.1k.orig.tar.gz
dpkg-source: info: building openssl using existing ./openssl_1.1.1k.orig.tar.gz.asc
dpkg-source: info: using patch list from debian/patches/series
patching file Configurations/unix-Makefile.tmpl
Hunk #2 FAILED at 825.
1 out of 2 hunks FAILED
patching file util/process_docs.pl
dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
dpkg-source: info: if patch 'man-section.patch' is correctly applied by quilt, use 'quilt refresh' to update it
dpkg-source: error: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -E -b -B .pc/man-section.patch/ --reject-file=- < openssl-1.1.1d.orig.eq8wGt/debian/patches/man-section.patch subprocess returned exit status 1
dpkg-buildpackage: error: dpkg-source -I -b . subprocess returned exit status 2
WARNING: exit code 2 from a shell command.


ERROR: Logfile of failure stored in: /build/tmp/work/iot2050-debian-arm64/openssl/1.1.1d-r0/temp/log.do_dpkg_build.79
ERROR: Task (/repo/recipes-security/openssl/openssl_1.1.1d.bb:do_dpkg_build) failed with exit code '1'
```


Followed by a second error :

```
 30450K .......... ....                                        5.70M=2m0s

2021-11-02 09:58:21 (254 KB/s) - Read error at byte 80969728 (Success.).Giving up.


ERROR: linux-iot2050-4.19.94+-r0 do_fetch: Fetcher failure for URL: 'https://git.ti.com/cgit/processor-sdk/processor-sdk-linux/snapshot/processor-sdk-linux-be5389fd85b69250aeb1ba477447879fb392152f.tar.xz'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /build/tmp/work/iot2050-debian-arm64/linux-iot2050/4.19.94+-r0/temp/log.do_fetch.76
ERROR: Task (/repo/recipes-kernel/linux/linux-iot2050_4.19.94+.bb:do_fetch) failed with exit code '1'
```

In attached, the complete log file

[log.do_.zip](https://github.com/siemens/meta-iot2050/files/7459740/log.do_.zip)

**Comment by jan-kiszka** [comment]
OK, but these are two issues:
 * openssl does not patch -> Try the trick on `./kas-container build kas-iot2050-example.yml --target openssl -c clean`
 * fetching of the kernel tarball fails (testing here as well, connection to TI is slow...) -> Are you behind a proxy? Does it work "from home" (real Internet)?

**Comment by jan-kiszka** [comment]
Actually, a full `./kas-container --isar clean` might be better to resolve all build issues after downgrading the version. That still won't help with the fetch issues, though.

**Comment by jan-kiszka** [comment]
Fetching works in principle, at least here, at least when calling manually `wget -t 2 -T 30 --passive-ftp --no-check-certificate 'https://git.ti.com/cgit/processor-sdk/processor-sdk-linux/snapshot/processor-sdk-linux-be5389fd85b69250aeb1ba477447879fb392152f.tar.xz'`.

**Comment by MickaelDelanoe** [comment]
I could completed my build after using`./kas-container --isar clean` 

Thank you.
