### ISSUE TITLE
GPIO - Copy-pasting a DIN node breaks some functionality

### ISSUE THREAD

**Issue by Webbeh** [siemens/meta-iot2050#245]
Build from yesterday, patches applied (especially #212)

/!\ Node-red updated to 2.1.4

Copy-pasting a DIN node that has the " Send initial message with level of pin." option enabled breaks that function.

It is still broken after a node-red restart from its GUI, or by restarting the systemd service.

Here's an example.

https://youtu.be/c-uMire1idE

**Comment by jan-kiszka** [comment]
Thanks for reporting! @fr0st61te, could you have a look what happens here?

**Comment by Webbeh** [comment]
Today, I tried to simply add a new DIN with the correct settings, and that one didn't work either. It was on the very first run of Node-red.

Is there maybe a timing issue between the flow restart and the activation of the pin?


I'd like to specify as well that Node-Red projects are enabled, although I highly doubt that will make any sort of difference.

**Comment by fr0st61te** [comment]
@Webbeh Could you please provide your "function" code?

**Comment by Webbeh** [comment]
Oh it just inverts the payload.

```js
return { payload:!msg.payload }
```

**Comment by fr0st61te** [comment]
I made the same scheme that you have in video with same codeblock in function which you proposed but I have the trigger just once on deploy(which seems ok from #212) and it didn't even reach the function block as I see. So, question is - am I missing something in scheme?

**Comment by Webbeh** [comment]
So the trigger works on deploy for you after copy-pasting the node ?

Odd...

I don't think there's anything that you're missing in your flows. I guess the only variant is that node-red has been updated and it might break something.

**Comment by jan-kiszka** [comment]
Oh, you have updated Node-RED manually - missed that "detail". Can you reproduce the problem also with the original image then?

We will likely update Node-RED "officially" for our next major release as well, and maybe then we will see the same issue.

**Comment by Webbeh** [comment]
I haven't tried. We needed an up-to-date image and I haven't tried with the original image. I'll report back once I did it, I have a few devices to setup in a week or two.

To be fair, the only annoying point right now is MRAA not compiling for NodeJS 16+...

**Comment by fr0st61te** [comment]
> So the trigger works on deploy for you after copy-pasting the node ?
> 

Yes, I tried it today again and it works as expected.

**Comment by jan-kiszka** [comment]
> To be fair, the only annoying point right now is MRAA not compiling for NodeJS 16+...

If that topic is generic (reproducible without this layer), please do not hesitate to file an issue on https://github.com/eclipse/mraa/ (if there is nothing related already).

But note that we will not update to a NodeJS version without Debian support because that will cause too much additional integration and maintenance effort. Updating Node-RED is more realistic - or does it depend on NodeJS > 12 already?

**Comment by Webbeh** [comment]
I believe Node-red 3 (end of April 2022) is the first one who's gonna drop support for Node 12.

**Comment by jan-kiszka** [comment]
Do you have a pointer for this plan? So far, support goes way back, even down to Node JS 8.x.

**Comment by jan-kiszka** [comment]
Reopen if issues persist with latest master.
