### ISSUE TITLE
Digital input node from Siemens cusing Node-Red to abort

### ISSUE THREAD

**Issue by MohammadKurdia** [siemens/meta-iot2050#250]
I have a configuration where 6 digital inputs are connected to 6 digital outputs. 

When I turn on and off the digital output, I read the signal in node red using the Digital input node provided from Siemens. 

But after some minutes of running this flow, Node-Red aborts for some reason !!

![Node-Red_Abort_Message](https://user-images.githubusercontent.com/34815611/149928251-592e11ad-91e4-44bf-8648-ad957b87586a.png)

I replaced these digital input nodes with exec nodes with "Mraa" commands in them. and now it's working fine.

**Comment by MohammadKurdia** [comment]
Example image V1.1.1

**Comment by jan-kiszka** [comment]
Can you re-check with V1.2.1 as well? Note that this requires a firmware update as well.

**Comment by MohammadKurdia** [comment]
Where can I find the V1.2.1 ?

**Comment by jan-kiszka** [comment]
Not yet uploaded apparently... Please request via forum, direct message to bergmanu. Both the image and the firmware update package.

**Comment by jan-kiszka** [comment]
I suppose this was resolved by now.
