### ISSUE TITLE
very slow boot

### ISSUE THREAD

**Issue by federico-d** [siemens/meta-iot2050#251]
On v01.01.01 the example image (kas-iot2050-example.yml) boots very slowly due to crng init:

[   10.066721] pru-rproc b206000.rtu: PRU rproc node rtu@b206000 probed successf                                                                                                                                                             ully
[   10.279217] icssg-prueth pruss0_eth: TI PRU ethernet driver initialized: dual                                                                                                                                                              EMAC mode
[   33.846080] tps62363-vout: disabling
[  136.918242] random: crng init done
[  136.921663] random: 7 urandom warning(s) missed due to ratelimiting

is there a way to speed it up?
Thanks

**Comment by jan-kiszka** [comment]
Is this without any network attached? Does the issue vanish when bringing the device online?

Was this a self-built image? Same issue when using the release binary version? Also, can you reproduce this with the latest image release (make sure to update the firmware for that first)?

**Comment by federico-d** [comment]
> Is this without any network attached? Does the issue vanish when bringing the device online?
It doesn't matter, it happens at every boot.
> 
> Was this a self-built image? Same issue when using the release binary version? Also, can you reproduce this with the latest image release (make sure to update the firmware for that first)?
Yes, it is a self built image. I solved it (temporarily?) by adding -haveged- debian package that seems to speed up entropy accumulation.
One thing I noticed, the ti rng doesn't show up in the device tree and looks disabled.

**Comment by jan-kiszka** [comment]
Is this an advanced or a basic variant?

And, again, do you get the same behavior when using the binary images that was released? I'm still confused that he haven't seen that before.

**Comment by federico-d** [comment]
Its a basic version. I never used the stock image, could you point me to
the download link?

**Comment by jan-kiszka** [comment]
Sure: https://support.industry.siemens.com/cs/document/109741799/downloads-for-simatic-iot20x0?dti=0&lc=en-WW#!

**Comment by jan-kiszka** [comment]
Probably solved by now.
