### ISSUE TITLE
Error integrating docker （branch:remotes/origin/stable/V01.02）

### ISSUE THREAD

**Issue by lxmuyu** [siemens/meta-iot2050#262]
When I  integrated docker.io into source, using 
```
IMAGE_PREINSTALL += " \
...
docker.io \
    "
```
, I got the error:
```

Configuration file '/etc/hosts'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** hosts (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package customizations-base (--configure):
 end of file on stdin at conffile prompt

...

done.
done.
Processing triggers for dbus (1.12.20-2) ...
Processing triggers for initramfs-tools (0.140) ...
update-initramfs: Generating /boot/initrd.img-5.10.64
Errors were encountered while processing:
 customizations-base
E: Sub-process /usr/bin/dpkg returned an error code (1)
WARNING: exit code 100 from a shell command.


DEBUG: Python function do_rootfs_install finished

```

How can I fix it ? 

[log.do_rootfs_install.97.txt](https://github.com/siemens/meta-iot2050/files/8039172/log.do_rootfs_install.97.txt)

**Comment by lxmuyu** [comment]
![截图_选择区域_20220210162337](https://user-images.githubusercontent.com/32975142/153367609-37660629-fd10-4550-b7d3-ee2f41d02608.jpg)



When I modifie `customizations-base_0.1-iot2050-debian.bb` file , delete :
```
install -v -m 644 ${WORKDIR}/hosts ${D}/etc/
```

compile is ok....
![截图_选择区域_20220210162443](https://user-images.githubusercontent.com/32975142/153367665-0b67e568-bd85-4709-aaff-3da0ec232b82.jpg)

**Comment by jan-kiszka** [comment]
We likely need to move /etc/hosts out of the ownership of customizations-base while still filling it (i.e. move it to the postinst script). Things worked so far when installing docker manually on the device. Your case was apparently not tested so far, but it is valid. Interestingly, docker.io will not come to a different /etc/hosts than customizations-base.

**Comment by lxmuyu** [comment]
Docker.io should not affect /etc/hosts, but the error came.
Beside Docker.io, I has installed mariadb-server,nginx,logrotate and docker-compose. Only the Docker.io made error, It's strange.

**Comment by lxmuyu** [comment]
Docker.io should not affect /etc/hosts, but the error came.
Beside Docker.io, I has installed mariadb-server,nginx,logrotate and docker-compose. Only the Docker.io made error, It's strange.

The same softs were added to the tag V01.01.01.That is all fine....

**Comment by lxmuyu** [comment]
> We likely need to move /etc/hosts out of the ownership of customizations-base while still filling it (i.e. move it to the postinst script). Things worked so far when installing docker manually on the device. Your case was apparently not tested so far, but it is valid. Interestingly, docker.io will not come to a different /etc/hosts than customizations-base.

Docker.io should not affect /etc/hosts, but the error came.
Beside Docker.io, I has installed mariadb-server,nginx,logrotate and docker-compose. Only the Docker.io made error, It's strange.

The same softs were added to the tag V01.01.01.That is all fine....

**Comment by jan-kiszka** [comment]
Let me look into that... Should be quick to resolve, and the I will propose that for the stable branch as well.
