### ISSUE TITLE
4G activation via iot2050setup

### ISSUE THREAD

**Issue by Tom-RCNL-DI-FOA** [siemens/meta-iot2050#27]
Hello,

I've been trying to activate my 4G module:
Huawei ME909s-120p

I get it working by manually enter the AT commands on the device, by using "picocom -b 115200 /dev/ttyUSB2" , but activation via iot2050setup doesn't do anything.

I want it to start up while booting, right now I need to manually enter these commands to get internet.

Do you have any suggestions?

With kind regards,

Tom Visser

**Comment by jan-kiszka** [comment]
If you solved it, do not hesitate to drop a note on how. That may also lead to better documentation.
