### ISSUE TITLE
Accessing user button

### ISSUE THREAD

**Issue by sivakatru** [siemens/meta-iot2050#271]
What is the GPIO number for User button for v1.2.1?

Tried with all GPIO pins and none seems to work!

**Comment by jan-kiszka** [comment]
`gpiomon $(gpiofind USER-button)`. Do not rely on numbering under `/sys/class/gpio`, though are conceptually unstable.

**Comment by sivakatru** [comment]
Thanks @jan-kiszka for the quick reply. 
Let me check it and get back.
