### ISSUE TITLE
Using SPI Flash Programmer

### ISSUE THREAD

**Issue by delarosa1962** [siemens/meta-iot2050#277]
I have to upgrade many IOT 2050 to F/W version 1.2.1 -- the current process is rather lengthy and would like to have all the steps to use the SPI Programmer.  What Image do I use ? What is the exact process ?

**Comment by delarosa1962** [comment]
> Did you study https://github.com/siemens/meta-iot2050/blob/master/recipes-bsp/u-boot/README.md already? It describes the steps needed for programming externally (if that is what you mean with "use the SPI Programmer").

Yes, that is what I was looking for. X17 header. Then the question is the file format ? There are two types of images that could be sent, the firmware itself and the OS. Could both be done using the DediProg programmer ?

**Comment by jan-kiszka** [comment]
X17 only attaches to the QSPI flash.

**Comment by delarosa1962** [comment]
Hi, I purchased the SF 100, the X17 has 8 pins but the SF 100 cable has 14.  What specific cable part # do I need to get to be able to flash the f/w ?

**Comment by lifang0504** [comment]
hello i think you need one of this cable , can transfer 14 pins to 8 pins. 

![image](https://user-images.githubusercontent.com/82988200/160511394-d73973e1-63e2-431e-8294-0b83749cf359.png)

**Comment by delarosa1962** [comment]
Yes, thanks. I ordered one, part number is:
https://www.dediprog.com/product/ISP1-CB
