### ISSUE TITLE
Use of DS18B20 temperature sensor with onewire bus

### ISSUE THREAD

**Issue by Tom-RCNL-DI-FOA** [siemens/meta-iot2050#28]
Hello,

I'm trying to use a DS18B20 sensor straight via the terminals of the IOT2050.

I've changed the defonfig_base file [https://github.com/siemens/meta-iot2050/blob/2a63d44e4eb97930c9dc7172bc4e202ef299a30d/recipes-kernel/linux/files/iot2050_defconfig_base](url) by adding the following lines:
CONFIG_W1_SLAVE_THERM=m
CONFIG_W1_MASTER_GPIO=m

After this I rebuild the image and now I can do 'modprobe w1-therm && modprobe w1-gpio'. So far so good.

Now I need to add the onewire devices to the devicetree but it seems not in the image, is that right?

Could you please check what I need to do to use these temperature sensors?

Thank you very much,

Tom Visser 
RC-NL FOA

**Comment by jan-kiszka** [comment]
Yes, there is nothing in the device tree.

If I interpret https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/w1/w1-gpio.txt correctly, you just need to add such snippet with the right GPIO number to the existing DT. Or use a DT overlay, but that is likely not enabled in our kernel yet.

Do you already have the right snippet available?

**Comment by Tom-RCNL-DI-FOA** [comment]
Hello Jan,



Some webpage I found does the following:

First add the device definition in your devices devicetree (assuming 1-wire device is connected to PD2 pin):

onewire_device {

   compatible = "w1-gpio";

   gpios = <&pio 3 2 GPIO_ACTIVE_HIGH>; /* PD2 */

   pinctrl-names = "default";

   pinctrl-0 = <&my_w1_pin>;

};



And then define the pins under &pio label:

&pio {

   ...



   my_w1_pin: my_w1_pin@0 {

     allwinner,pins = "PD2";

     allwinner,function = "gpio_in";

     allwinner,drive = <SUN4I_PINCTRL_10_MA>;

     allwinner,pull = <SUN4I_PINCTRL_PULL_UP>;

   };



   ...

};



Is this what you mean with snippet?



Met vriendelijke groet,
Tom Visser

Siemens Nederland N.V.
RC-NL DI FA FOA
Prinses Beatrixlaan 800
2595 BN Den Haag, Nederland
Tel.: +31 612320728
mailto:tom.visser@siemens.com
www.siemens.com/ingenuityforlife<https://siemens.com/ingenuityforlife>






Van: Jan Kiszka <notifications@github.com>
Verzonden: woensdag 1 juli 2020 12:29
Aan: siemens/meta-iot2050 <meta-iot2050@noreply.github.com>
CC: Visser, Tom (RC-NL DI FA FOA) <tom.visser@siemens.com>; Author <author@noreply.github.com>
Onderwerp: Re: [siemens/meta-iot2050] Use of DS18B20 temperature sensor with onewire bus (#28)



Yes, there is nothing in the device tree.

If I interpret https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/w1/w1-gpio.txt<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Ftorvalds%2Flinux.git%2Ftree%2FDocumentation%2Fdevicetree%2Fbindings%2Fw1%2Fw1-gpio.txt&data=02%7C01%7Ctom.visser%40siemens.com%7Ce6e65963894543e5fe6e08d81da9c1f3%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637291962222593685&sdata=3NldG8Wxd8KFM%2FBAZrKiYnSJE8u6Jo9K5PFeE2gmYFo%3D&reserved=0> correctly, you just need to add such snippet with the right GPIO number to the existing DT. Or use a DT overlay, but that is likely not enabled in our kernel yet.

Do you already have the right snippet available?

**Comment by jan-kiszka** [comment]
Yes, this looks similar, though it will not fit as-is (it is referring to an Allwinner SoC).

So you need to solve two issues:
 - inject a snippet into the DT that is built for the IOT2050
 - figure out what exactly is needed here

For the first point, create a patch that targets arch/arm64/boot/dts/siemens/iot2050-common.dtsi, then hook up that patch with https://github.com/siemens/meta-iot2050/blob/master/recipes-kernel/linux/linux-iot2050_4.19.59%2B.bb. The second point might be tricker, though, will likely involve a bit of trial and error. Which GPIO pin are your targeting exactly?

**Comment by Tom-RCNL-DI-FOA** [comment]
Hello Jan,



Thank you for your reply.

I’m not a linux/RPI/microcontroller-specialist but I guess I’ll try to figure out what you told me haha.



Btw I did add the config-parts for w1-therm, w1-gpio and ch341 (for usb serial comm) to my built-files.

After this  ‘sudo modprobe w1-therm || modprobe w1-gpio’ was possible, unfortunately the w1-therm/w1-gpio didn’t recognize the sensors, while my Arduino nano immediately sees the sensor.



In the meantime the customer decided to use different sensors (PT100) but we’d still like to be able to use these sensors because they are pretty good and a lot of people use them (on RPI).



We’d like to use any port as may possible, is there a default port to use for this?

RPI uses GPIO4 (pin 7) for this kind of sensors by default.



With kind regards,



Tom Visser



Van: Jan Kiszka <notifications@github.com>
Verzonden: woensdag 8 juli 2020 17:03
Aan: siemens/meta-iot2050 <meta-iot2050@noreply.github.com>
CC: Visser, Tom (RC-NL DI FA FOA) <tom.visser@siemens.com>; Author <author@noreply.github.com>
Onderwerp: Re: [siemens/meta-iot2050] Use of DS18B20 temperature sensor with onewire bus (#28)



Yes, this looks similar, though it will not fit as-is (it is referring to an Allwinner SoC).

So you need to solve two issues:

*       inject a snippet into the DT that is built for the IOT2050
*       figure out what exactly is needed here

For the first point, create a patch that targets arch/arm64/boot/dts/siemens/iot2050-common.dtsi, then hook up that patch with https://github.com/siemens/meta-iot2050/blob/master/recipes-kernel/linux/linux-iot2050_4.19.59%2B.bb<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsiemens%2Fmeta-iot2050%2Fblob%2Fmaster%2Frecipes-kernel%2Flinux%2Flinux-iot2050_4.19.59%252B.bb&data=02%7C01%7Ctom.visser%40siemens.com%7Cce072e5918394dfa126b08d8235030aa%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637298174600373287&sdata=H9FRQXkUboHdxpzDpGGE0c5GaBkg6JLYJ29TZlMoNcg%3D&reserved=0>. The second point might be tricker, though, will likely involve a bit of trial and error. Which GPIO pin are your targeting exactly?

**Comment by jan-kiszka** [comment]
There is no default GPIO for this. You need to pick one, specify that in the device tree node that describes the w1-gpio, and then start the device with that DT. Just loading the drivers does not work because Linux drivers are configured via DT, not via hard-coded parameters like it is the case on the more simplistic Arduinos.

**Comment by Tom-RCNL-DI-FOA** [comment]
Hello Jan,



Thank you for your response, unfortunately I’ve been searching for this devicetree but I can’t find it.
Is this something I need to install?



Met vriendelijke groet,
Tom Visser

Siemens Nederland N.V.
RC-NL DI FA FOA
Prinses Beatrixlaan 800
2595 BN Den Haag, Nederland
Tel.: +31 612320728
mailto:tom.visser@siemens.com
www.siemens.com/ingenuityforlife<https://siemens.com/ingenuityforlife>






Van: Jan Kiszka <notifications@github.com>
Verzonden: donderdag 9 juli 2020 11:49
Aan: siemens/meta-iot2050 <meta-iot2050@noreply.github.com>
CC: Visser, Tom (RC-NL DI FA FOA) <tom.visser@siemens.com>; Author <author@noreply.github.com>
Onderwerp: Re: [siemens/meta-iot2050] Use of DS18B20 temperature sensor with onewire bus (#28)



There is no default GPIO for this. You need to pick one, specify that in the device tree node that describes the w1-gpio, and then start the device with that DT. Just loading the drivers does not work because Linux drivers are configured via DT, not via hard-coded parameters like it is the case on the more simplistic Arduinos.

**Comment by jan-kiszka** [comment]
Oops, didn't reply back then. I suppose this issue is obsolete now. Feel free to reopen if not.
