### ISSUE TITLE
Access to GPIOs only with root privileges

### ISSUE THREAD

**Issue by bergmanu** [siemens/meta-iot2050#281]
Access to the Arduino GPIOS via bash programms "mraa-gpio", "mraa-uart" and "mraa-i2c" is only working logged in as root or using sudo being logged in as user. 

Calling the programs as user results in "free(): invalid pointer" 
![image](https://user-images.githubusercontent.com/22653568/158323303-9f13a882-8822-412d-9fb2-ff4e6a9cb9b9.png)

Is this intended? Is there any other way to access GPIOs as user without using sudo?

**Comment by jan-kiszka** [comment]
You can try `chown`ing the sysfs nodes that have to be accessed and can be securely forwarded.

That `free()` bug is likely a error in some cleanup path. Needs to be analyzed.

**Comment by jan-kiszka** [comment]
@fr0st61te, could you eventually have a look if / what goes wrong there in mraa when it calls that wrong free()? TIA.

**Comment by bergmanu** [comment]
> You can try `chown`ing the sysfs nodes that have to be accessed and can be securely forwarded.
> 
> That `free()` bug is likely a error in some cleanup path. Needs to be analyzed.

Tried to `chown` the whole _/sys/class/gpio_ directory recursively, still same output

**Comment by jan-kiszka** [comment]
Just recalling: We also use direct MMIO access for configuring the pins in mraa. That involves using /dev/mem - a no-go for anything unprivileged. So, this is doomed to fail.

**Comment by fr0st61te** [comment]
> @fr0st61te, could you eventually have a look if / what goes wrong there in mraa when it calls that wrong free()? TIA.

Sure, I'll take a look!

**Comment by jan-kiszka** [comment]
Merged into master, happily looking for more testers now!
