### ISSUE TITLE
GPIO DIs only show 0 (Basic PG2)

### ISSUE THREAD

**Issue by bergmanu** [siemens/meta-iot2050#284]
A customer in forum is describing that the DIs of the Arduino GPIOs are not working with IOT2050 Basic PG2- they only show 0, even if 24V is connected. Customer tried node-red nodes and the mraa-gpio tool

Customer setup: 
- IOT2050 Basic FS:02 (PG2) 
- Siemens I/O Module
- Example Image V1.2.1
- mraa-gpio tool
- node-red nodes

More info see [here](https://support.industry.siemens.com/tf/ww/en/posts/trouble-reading-digital-input-pins/278302/?page=0&pageSize=10#post1075969)

I do not have a PG2 device at the moment. Could someone test that? 
Will check it with PG1 next week in office.

**Comment by bergmanu** [comment]
I tested with IOT2050 PG1 in different cominations. GPIOs work on all of them! 

1. Firmware V1.0.0 with Example Image V1.1.1
2. Firmware V1.2.1 with Example Image V1.1.1
3. Firmware V1.2.1 with Example Image V1.2.1

Connected a DQ of a S7-1500 to DI0 of the Siemens Input/Output Module and checked its status via `mraa-gpio get 12` and the value changed between 0 and 1, depending whether the S7-1500 DQ is 0 or 1.

**Comment by GQ411** [comment]
It's no occurred on my test environment.
Hardware: 
`iot2050 PG2 Basic + iot2000 i/o MODULER (6ES7647-0KA01-0AA2) FS 01`

software:
```
firmware V01.02.01_40d3fc0_20220106.
seboot_version: V01.02.01.04-0-g398B965C-0X000
```

Test:

1 connect with 24V to pin 12,  **mraa-gpio get 12**, it return **1**;
2 disconnect 24V form pin 12, **mraa-gpio get 12**, it return **0**;


it not reproduce on my environment.

**Comment by chris0z** [comment]
Have the same issue 
IOT2050 Advanced FS:05 image V1.2.2
I changed the Jumper like described in the manual

Test:
1 connect with 24V to pin 12, mraa-gpio get 12, it return 0;
2 disconnect 24V form pin 12, mraa-gpio get 12, it return 0;

**Comment by jan-kiszka** [comment]
I hope you didn't use 24V on the bare IO12 pin: without an I/O shield like https://mall.industry.siemens.com/mall/en/WW/Catalog/Product/6ES7647-0KA01-0AA2, those pins are 0..5V only (@bergmanu, correct me if I'm wrong).

**Comment by chris0z** [comment]
Yes i used this 6ES7647-0KA01-0AA2 for my setup

**Comment by chris0z** [comment]
You have to wire the specific GND pin to GND in my case M0 to GND. Than its working fine. Its not connected internally to the GND as expected. Hope that helps.
