### ISSUE TITLE
4G card - IOT2050 - connection lost

### ISSUE THREAD

**Issue by ikramid** [siemens/meta-iot2050#311]
Hello,

I aim to use a 4G card (Telit LE910C1-EU) with my IOT2050, but as soon as I plug it, I lost the connection on Putty.
I don't think it is a driver issue, but don't know what could it be.

Do you have any idea about the source of the problem ?

Thanks.

**Comment by lifang0504** [comment]
Hello, do you have any mpcie pin definition document about this 4G card  (Telit LE910C1-EU)  ? We met this problem before when using ZTE 4G ME3630 , we need to double check if it is the same problem.

thank you so much .

**Comment by ikramid** [comment]
Hello,

I have the document attached. I think that it's what you need.
If it's not, please tell me to find the right one.

Many thanks in advance.
________________________________
De : lifang0504 ***@***.***>
Envoyé : vendredi 6 mai 2022 03:29
À : siemens/meta-iot2050 ***@***.***>
Cc : Ikram Idrouss (Student at CentraleSupelec) ***@***.***>; Author ***@***.***>
Objet : Re: [siemens/meta-iot2050] 4G card - IOT2050 - connection lost (Issue #311)


Hello, do you have any mpcie pin definition document about this 4G card (Telit LE910C1-EU) ? We met this problem before when using ZTE 4G ME3630 , we need to double check if it is the same problem.

thank you so much .

**Comment by lifang0504** [comment]
Hello, did you send the document via email ? But can't find this document, so can you send it again. 
thank you so much!

**Comment by ikramid** [comment]
[Telit_LE910Cx_Interface_Board_Hardware_Design_Guide_r4.pdf](https://github.com/siemens/meta-iot2050/files/8652533/Telit_LE910Cx_Interface_Board_Hardware_Design_Guide_r4.pdf)
Hello,
Here's the attached file.

Thank you

**Comment by lifang0504** [comment]
Hello,
Have received. I will ask HW colleagues to check that, if get any response will reply asap.
thank you so much!

**Comment by lifang0504** [comment]
Hello,

What's pity, this is not we want. 
We want the **minipcie pin definition** of this 4G module(Telit LE910C1-EU), same as below. Can you help to provide ? Thank you so much!
![image](https://user-images.githubusercontent.com/82988200/167529612-3cde316b-401c-4e4c-b155-780f4c157f4a.png)

**Comment by ikramid** [comment]
Hello,

Unfortunately, it is shown in any picture, but according to technical support of the card manufacturer, the card  follows the standard mPCIe layout of the pins. So odd numbers on the top side and even numbers on the bottom side.

We had an old version of the same card which work properly, but the recent version isn't.
The difference between the two versions is a pinout change. Please find the change on the attached picture.
![pinoutçchange](https://user-images.githubusercontent.com/92576998/171828432-082b29ab-d59b-4e51-825e-75d2adfaf41f.PNG)

Do you think that it might me the problem ?

Thank you .

**Comment by lifang0504** [comment]
Can you give me all mPCIe pin definition not just the pin 47 and pin 49 of this Telit LE910C1-EU? Due to different card maybe have different pin definition . Because we didn't have this card so our hardware colleagues need the whole pin definition to do research on this problem .
**such as below picture, the pin definition from pin1 to pin52.**
![image](https://user-images.githubusercontent.com/82988200/172082601-d52ef2dd-164b-41f4-9775-517999325cc2.png)
![image](https://user-images.githubusercontent.com/82988200/172082712-98ac94e1-0009-45ac-a42c-dd48712ff8e7.png)


can you provide this information ? thank you so much!

**Comment by BaochengSu** [comment]
Please make sure the new revision of the module is using PCIE signal, not the USB3.0 signal. We noticed there were some modules using usb3.0 by default, see issue #109

**Comment by jan-kiszka** [comment]
I suppose this is resolved.
