### ISSUE TITLE
preinstall local node-red node to image

### ISSUE THREAD

**Issue by applea9** [siemens/meta-iot2050#316]
Hi,

I have created a node-red node locally, which is not published in the npm registry. 

I would like to preinstall this node in the image, could you give some hints how to achieve it?

Thanks very much.

**Comment by jan-kiszka** [comment]
Have a look at https://github.com/siemens/meta-iot2050/tree/master/recipes-app/node-red-gpio. Your recipe could be fairly similar, except for where the node sources would come from (maybe in-tree, file://, maybe from another local repo).

**Comment by applea9** [comment]
Thanks for your answer.

When I install npm package with npm.bbclass, I want to add extra custom arguments in addition to the predefined npm arguments. After checking the npm.bbclass file, I didn't find such options. Is it possible to do it?

**Comment by jan-kiszka** [comment]
npm.bbclass is for pulling pre-packaged nodes from npmjs.com. That's not suited here and therefore also not used by the example I cited.

**Comment by applea9** [comment]
Ok, Thanks a lot.
