### ISSUE TITLE
Support users with WIFI firmware

### ISSUE THREAD

**Issue by jan-kiszka** [siemens/meta-iot2050#34]
We should either preinstall more firmware packages, e.g. firmware-brcm80211, or offer some logic via iot2050setup to identify and install them from there, when the user tries to configure a network device.

**Comment by BaochengSu** [comment]
Due to the long clearing process, I perfer the iot2050setup way.

**Comment by jan-kiszka** [comment]
Well, it targets the next release anyway, thus also a general package update. I'm slightly optimistic that modern firmware packages should not trigger any licensing concern. IIRC, we only had findings in legacy firmware. And Debian splits this up, thus we can cherry-pick.

**Comment by bergmanu** [comment]
Hi, 
I'd really appreciate the support of more WiFi firmware. 
We have to clear the new version anyway, so maybe preinstalling more firmware does not blow up the clearing process.

But of course I'd also be happy with "semi-manual" installing via setup tool. But I guess this is means more effort in development, right?
