### ISSUE TITLE
ufw ipv6 support

### ISSUE THREAD

**Issue by STD-FP** [siemens/meta-iot2050#357]
I tried to install ufw on the image created with version V01.03.01

when you enable the firewall with
`sudo ufw enable`

```
ERROR: problem running ufw-init
ip6tables-restore v1.8.7 (nf_tables): Couldn't load match `rt ': No such file or directory

Error occurred at line: 24
Try `ip6tables-restore -h 'or' ip6tables-restore --help 'for more information.

Problem running '/etc/ufw/before6.rules'
```

I then ran 
`sudo check-requirements`
under ./usr/share/ufw/

and all tests report problems on the ipv6 part

anyone have any suggestions?

Note:
same isssue wuth release v01.02.02
if i disabled the ipv6, all is OK

**Comment by jan-kiszka** [comment]
You likely need to configure some extra kernel features for IPv6. Does the report tell more about what is missing?

**Comment by jan-kiszka** [comment]
Please answer my question and re-open if still relevant.
