### ISSUE TITLE
Interface change in specification of NPM build dependencies

### ISSUE THREAD

**Issue by fmoessbauer** [siemens/meta-iot2050#378]
Before the sbuild integration, additional NPM install / build dependencies could be added to `NPM_EXTRA_DEPS`. With sbuild support, these now have to be listed twice: in the `NPM_EXTRA_DEPS` and in `DEBIAN_BUILD_DEPENDS`. The reason is, that the sbuilder uses the dependencies listed in `debian/control`, while the `do_install_npm` task uses `NPM_EXTRA_DEPS`.
Also, the format of both variables has to be different (space separated vs. debian depends format).

I don't know if this is intentional, or if we should add logic that creates a comma separated list of `NPM_EXTRA_DEPS` and adds it to `DEBIAN_BUILD_DEPENDS`.

Real-world example:

```
NPM_EXTRA_DEPS = "libzmq3-dev"
DEBIAN_BUILD_DEPENDS .= ",libzmq3-dev"
```

**Comment by jan-kiszka** [comment]
I think this turned out to be not needed. Moreover, NPM_EXTRA_DEPS will be history with #456 (just cleaning up its last bits).
