### ISSUE TITLE
version of the iot2050-setup tool never bumped

### ISSUE THREAD

**Issue by chombourger** [siemens/meta-iot2050#385]
The tool was introduced 3 years ago with version 0.1
several features were added since then but the version is still 0.1 and several versions of this distribution were released
versions (and changelogs) should be maintained especially for binary distributions that are consuming your recipes (e.g. to support apt dist-upgrade scenario)

**Comment by jan-kiszka** [comment]
We likely have that issue not only in this context, possibly also for other self-written packages. Any suggestions how to make sure that we do not miss recipe version bumps on tool updates?

For this tool, it would probably the first step to add a version to it that is also somewhere tracked in the code - and then reflected also in the recipe.

**Comment by jan-kiszka** [comment]
iot2050-setup became board-conf-tools and that did not run into the same issue so far.
