### ISSUE TITLE
IOT2050 does not boot with network cable connected to X1P2 dhcp

### ISSUE THREAD

**Issue by bergmanu** [siemens/meta-iot2050#389]
Issue on behalf of a customer in the forum: 

When I boot the Iot2050 everything works. 
When I boot it with a network cable connected to the lower network port (X1P1: 192.168.200.1) everything works fine. 
But when I connect it to our network with cable connected to the top network port (X1P2: DHCP) then it doesn't boot (red STAT led). When I boot the device without any cable connected and wait till it's booted, and then connect the cable to our network, then it gets an IP address assigned and I can find it and everything works.

Is there a problem booting when connected to a network? Can I do something about this? 
IOT2050 Advanced FS:05 with Example Image V1.2.2

Have we ever encountered this somewhere else?

**Comment by bergmanu** [comment]
Could not reproduce the issue with FS:04

**Comment by jan-kiszka** [comment]
Where in the boot does the device get stuck? Do you have any debug console output?

**Comment by bergmanu** [comment]
Seems that the issue was caused by a strangely behaving UART cable and has nothing to with the connected network. 
We can close this
