### ISSUE TITLE
Reset GPIO pins after/with shutdown / halt

### ISSUE THREAD

**Issue by gramss** [siemens/meta-iot2050#39]
GPIO states set via mraa + Python are not reset when the IOT is powered off via `shutdown now` or `halt`.
Only with a hard reset or `reboot`.

Can this be fixed easily?

**Comment by jan-kiszka** [comment]
This is fairly application specific. You could register a custom systemd unit that is run on shutdown and sets I/O into the desired state (via mraa).

**Comment by jan-kiszka** [comment]
https://www.golinuxcloud.com/run-script-with-systemd-before-shutdown-linux/

**Comment by gramss** [comment]
Thank you! This looks good to me! 👍
