### ISSUE TITLE
Overwrite with .bbappend recipe in new isar layer

### ISSUE THREAD

**Issue by applea9** [siemens/meta-iot2050#41]
Hello,

I am trying to overwrite some existing recipes(customizations-example, e.g.) in my own layer with .bbappend recipe.

For example, I would like to replace the postinst file in customizations-example recipe.

Following is my steps:

1) Follow the yocto way to set BBFILE_PRIORITY to 7 in layer.conf
2) Create postinst file with some modification in files folder
3) Add it in SRC_URI in .bbappend file.

But the result is postinst file is not replaced.

Could you give some advice? thanks a lot.

**Comment by jan-kiszka** [comment]
The key is something like `FILESEXTRAPATHS_prepend := "${THISDIR}/files:"` so that postinst is searched for in your own `files` folder.

**Comment by applea9** [comment]
> The key is something like `FILESEXTRAPATHS_prepend := "${THISDIR}/files:"` so that postinst is searched for in your own `files` folder.

Thanks for quick reply. you are right, I have FILESEXTRAPATHS_prepend := "${THISDIR}/files:" in yocto recipe.  I will try it.
