### ISSUE TITLE
Use GitHub "rebase and merge"

### ISSUE THREAD

**Issue by chombourger** [siemens/meta-iot2050#413]
The git history is IMO polluted with GH's merge commits. I would recommend using the "rebase and merge" option when merging approved Pull Requests

**Comment by jan-kiszka** [comment]
I would not mind (and do that myself elsewhere). Simplest way to achieve that is disabling "Allow merge commits" in the settings (just checked).
@BaochengSu

**Comment by BaochengSu** [comment]
Done.
