### ISSUE TITLE
Kernel OOPS while using rmmod for ethernet driver

### ISSUE THREAD

**Issue by sgthammer** [siemens/meta-iot2050#427]
Hello,

For an image with swupdate support, I tried to remove ethernet driver module using _rmmod_. "**rmmod iccsg_prueth**" command is used for this aim and the _rmmod_ throws segmentation fault. Also, kernel throws OOPS as internal error. Kernel log file is attached.

What could be the reason causes this issue?
[oops.log](https://github.com/siemens/meta-iot2050/files/11090619/oops.log)

**Comment by nhahnetsrot** [comment]
Pls. try the attached patch, needs to be copied to meta-iot2050/recipes-kernel/linux/files/patches-5.10/ and then the image needs to be rebuild (e.g.: sudo kas-container clean; kas-container build )

[0211-fix-rmmod.patch](https://github.com/siemens/meta-iot2050/files/11551349/0211-fix-rmmod.patch)

**Comment by jan-kiszka** [comment]
Will be fixed by #491
