### ISSUE TITLE
WWAN interface changes name 

### ISSUE THREAD

**Issue by rFond** [siemens/meta-iot2050#460]
Hi,

I have a problem with the wwan interface which changes its name randomly on reboot. Is it possible to freeze this (like the serial port X30) ?

Thank's

**Comment by jan-kiszka** [comment]
Which interface of which driver? And to which service is the naming change an issue?

There is always the option to have an own udev rule to pin the interface name, but there also other ways to keep track of the same interface, e.g. MAC- based interface selection in NetworkManager.

**Comment by rFond** [comment]
I use mpcie interface with a 4G modem (all it's work correctly). When I do "ifconfig" randomly name of interface "wwan0" in (more of time) change for exemple to "xwwxcodm0".

It's a detail, but if I can fix its more.

For X30 for exemple you use udev rules ? (for me MAC Address change in function of IOT)

**Comment by jan-kiszka** [comment]
https://github.com/siemens/meta-iot2050/blob/master/recipes-core/customizations-example/files/20-assign-ethernet-names.rules

**Comment by jan-kiszka** [comment]
Please close if that helped.
