### ISSUE TITLE
docker fails to install on example image -> works on main-branch -> bump release-image

### ISSUE THREAD

**Issue by gramss** [siemens/meta-iot2050#51]
Hey there,

we have problems with installing the docker-engine (for arm64) with the latest released image.
It works fine with my custom build image from around June.
Would be great if we could create a more recent example image!

Thanks 👍

**Comment by jan-kiszka** [comment]
Yes, this issue is fixed in master and will be officially resolved with the next release.

**Comment by jan-kiszka** [comment]
Expected to work with latest V01.01.01.
