### ISSUE TITLE
Add mraa to the SDK build

### ISSUE THREAD

**Issue by bergmanu** [siemens/meta-iot2050#55]
Currently the IOT2050 patched mraa is not included in the SDK. 
Please include it in order to program GPIOs in C++

**Comment by bergmanu** [comment]
Do these commits mean mraa is now included when building the SDK? 
Or do they first need to be merged to master?

**Comment by jan-kiszka** [comment]
The change is pending for master. If you need it earlier, I can split that branch up and send a PR now.

**Comment by bergmanu** [comment]
Do you have a feeling when it will be merged?

**Comment by jan-kiszka** [comment]
Within this or next week, I would guess.

**Comment by bergmanu** [comment]
Ok, that should be fine. 
I have a customer waiting for it, but this or next week is sufficient I guess.
