### ISSUE TITLE
Overwrite a debian package using dpkg-prebuilt

### ISSUE THREAD

**Issue by SCordibella** [siemens/meta-iot2050#571]
Dear All, I am trying to update a package called wkhtml2pdf because the Debian 12 version doesn't work as I need and there is a version that works as expected published in deb format.

My problem is that I am not able to overwrite the "debian" version of the package.

I create a recipe called wkhtmltopdf and here is the simple content:
```
inherit dpkg-prebuilt

SRC_URI = "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.bookworm_arm64.deb"
SRC_URI[sha256sum] = "b6606157b27c13e044d0abbe670301f88de4e1782afca4f9c06a5817f3e03a9c"

PV="0.12.6.1-3"

# Only needed if recipe name != package name, as in this case. Or multiple
# packages are provided by a single recipe.
PROVIDES += "wkhtmltopdf"
```

I change the package inclusion from `IMAGE_PREINSTALL` to `IMAGE_INSTALL`, finally I try to force "my" package with this:
```
local_conf_header:
  fix-wkhtmltopdf-version:
    PREFERRED_VERSION_wkhtmltopdf = "0.12.6.1-3"
```
Am I missing something?

Thank you for your help,
Stefano.

**Comment by jan-kiszka** [comment]
You probably need to replace `IMAGE_PREINSTALL += "wkhtmltopdf"` with `IMAGE_INSTALL += "wkhtmltox"`, provided that prebuilt `wkhtmltox` is actually the same as Debian's `wkhtmltopdf`.

But what would be better and more sustainable is to work with Debian to update to official package to 0.12.6.1.
