### ISSUE TITLE
npm.bbclass doesn't support nodes without bundled dependencies

### ISSUE THREAD

**Issue by davimaf** [siemens/meta-iot2050#9]
Using last commit from `jan/preinstalled-node-red-nodes` I get an error that I have fixed but maybe could be committed for next release.

I would like to add the following two nodes: 
- node-red-contrib-ui-led@0.3.1
- node-red-node-ui-table@0.3.1

Analyzing `npm-shrinkwrap`.json files, these two nodes have a package tree like below, where there aren't additional dependencies except the node itself:
```
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "node-red-contrib-ui-led": {
      "version": "0.3.1",
      "resolved": "https://registry.npmjs.org/node-red-contrib-ui-led/-/node-red-contrib-ui-led-0.3.1.tgz",
      "integrity": "sha512-+45hYOA9RN2XiUQ2dFaz17uJ/5G61xePlvJfIXsGOerypW/2jSfXnMpsgaYD0itE6tahUIY+WbvmeokxybeDHw=="
    }
  }
}
```
I created the recipes folders inside `recipes-app` with `npm-shrinkwrap.json` file and the package bb file like the other node red nodes recipes inside the app folder.

When i run kas I get the following error for both nodes:
```
ERROR: Logfile of failure stored in: /work/build/tmp/work/isar-arm64/node-red-contrib-ui-led/0.3.1-r0/temp/log.do_fetch.581
ERROR: Task (/repo/recipes-app/node-red-contrib-ui-led/node-red-contrib-ui-led_0.3.1.bb:do_fetch) failed with exit code '1'
ERROR: node-red-node-ui-table-0.3.1-r0 do_fetch: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:fetch_npm(d)
     0003:
File: '/repo/classes/npm.bbclass', lineno: 162, function: fetch_npm
     0158:
     0159:    with open("package.json") as infile:
     0160:        json_objs = json.load(infile)
     0161:
 *** 0162:    deps = [d for d in json_objs['dependencies']]
     0163:    json_objs.update({'bundledDependencies': deps})
     0164:
     0165:    # update package.json so that all dependencies are bundled
     0166:    with open("package.json", 'w') as outfile:
**Exception: KeyError: 'dependencies'**
```

Looks like that the problem is on `json_obj` that doesn't have bundled dependencies.

To make it work, I have modified `npm.bbclass` file lines [162-163](https://github.com/siemens/meta-iot2050/blob/75d54eb656b7a704e0513395a8211744df1a7ba8/classes/npm.bbclass#L162) as below:

```
    deps = {}
    if 'dependencies' in json_objs.keys():
        deps = [d for d in json_objs['dependencies']]
        json_objs.update({'bundledDependencies': deps})
```

By adding an if statement to control if there are bundled dependencies.

Hope can it help

**Comment by jan-kiszka** [comment]
Good catch! Would you write a patch? Or should I?
